README.md, api/server.js, cars/cars-routerPG.js
=> Updates to Documentation

README.md
some errors remained in the docs after the last commit, this fixes the documentation
=> Fixed Docs

README.md
=> added coverage badges for maintainability and test coverage

README.md
=> fixed all of the markdown linter errors in the readme file

.npmrc, api/server.js, api/server.test.js, buildspec.yml
=> added buildspec and npmrc files

README.md, database/migrationsPG/20191217191729_create-users-table-pg.js
- [x ] This change requires a documentation update
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
=> updated docs for auth router

users/users-model.test.js, users/users-router.js, users/users-router.test.js
=> Feature/user router tests - unit tests added

jobs/jobs-router.test.js
=> Just adding a mockRestore to last test in file

jobs/jobs-router.js, jobs/jobs-router.test.js
- [X ] New feature (non-breaking change which adds functionality)
- [X ] Complete, tested, ready to review and merge
- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [X ] My code has been reviewed by at least one peer
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] I have made corresponding changes to the documentation
- [X ] My changes generate no new warnings
- [X ] I have added tests that prove my fix is effective or that my feature works
- [X ] New and existing unit tests pass locally with my changes
- [X ] There are no merge conflicts
=> slight clean up on job-router and job-router.test

.ebextensions/nginx.config
Fixing a bug in the max size of the photos
=> added nginx and ebextensions files to increase upload size

.ebextensions/nginx.config
=> trying another config file

.ebextensions/nginx.config
=> removing config file for beanstalk

.ebextensions/nginx.config, .ebextensions/nginx/conf.d/bodysize.conf
=> fixing upload size problem

auth/auth-routerPG.test.js, cars/cars-routerPG.test.js, package-lock.json, package.json, users/users-model.test.js
Broken tests from updated code
test runners
=> fixed all be tests for updated code

.ebextensions/increase_size.config, .ebextensions/nginx/conf.d/bodysize.conf
=> removing ebextensions files

jobs/jobs-model.js, jobs/jobs-router.js
=> Create new "find all jobs by washer id" router/model

README.md, jobs/jobs-model.js, jobs/jobs-router.js
=> Minor fix for new 'find all washer jobs" route, updated documentation.

.codeclimate.yml
added code climate config file
repeatability on maintainability
added a new file
=> added code climate yml to root

.codeclimate.yml, auth/auth-routerPG.js, users/users-router.js
number conversion
returning string value for float number
=> Location number conversion

auth/auth-routerPG.js, users/users-router.js
fixed issue with numbers returning as a string
fixed issue with numbers returning as a string
=> fixed floats for rates on washer

tests/cars-model.test.js, tests/users-router.test.js
Update tests for new additions
Failing tests
update
=> updated all tests for new additions

README.md, tests/users-router.test.js
=> added new showAvailableWashers endpoint to readme. fixed minor bug.

jobs/jobs-router.js, tests/jobs-router.test.js
=> added a catch error to the get all jobs endpoint and wrote a test for it

images/image-upload.js, users/users-router.js
=> fix integer showing as string. fix delete password function in images.

tests/auth-routerPG.test.js
Update Testing
failing tests due to updates
error messages
=> updated tests for new error return messages

README.md
Changed wording of docs link
confusion on deployed link
docs
=> changes wording of deployed link

images/image-upload.js
Fix bug on locations
returning string instead of float
bug fix
=> fixed string to float problem

auth/auth-routerPG.js, jobs/jobs-router.js
Changed format for creation date
string now returns only month day and year
update
=> changed date format for iOS team
